name: Build and Release XCFramework

on:
  push:
    tags:
      - "build*" # Trigger on version tags
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version (e.g., v1.0.0)"
        required: true
      prerelease:
        description: "Is this a pre-release?"
        required: true
        type: boolean
        default: false

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build XCFramework
        run: |
          chmod +x ./build_xcframework.sh
          ./build_xcframework.sh

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo ::set-output name=VERSION::${{ github.event.inputs.release_version }}
          else
            echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
          fi

      - name: Get checksum
        id: get_checksum
        run: |
          CHECKSUM=$(swift package compute-checksum GRDB.xcframework.zip)
          echo ::set-output name=CHECKSUM::$CHECKSUM

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            Release of version ${{ steps.get_version.outputs.VERSION }}

            Checksum: ${{ steps.get_checksum.outputs.CHECKSUM }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GRDB.xcframework.zip
          asset_name: GRDB.xcframework.zip
          asset_content_type: application/zip
